
services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    image: frontend
    ports:
      - "5573:80"
    depends_on:
      - backend

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    image: backend
    ports:
      - "5000:5000"
    environment:
      DB_USER: postgres
      DB_HOST: db
      DB_DATABASE: sistema_de_inscripcion
      DB_PASSWORD: 01092003
      DB_PORT: 5432
    depends_on:
      - db

  db:
    image: postgres:16
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 01092003
      POSTGRES_DB: sistema_de_inscripcion
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5433:5432"


volumes:
  postgres_data:
