name: CI workflow

on:
  push:
    branches:
      - main

jobs:
  run-linter-and-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          cd backend  # Si 'package.json' está en la carpeta backend
          npm install

      - name: Lint code
        run: |
          cd backend  # O el directorio adecuado
          npm run lint

      - name: Run tests
        run: |
          cd backend  # O el directorio adecuado
          npm test
